/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPeriodReport.java
 *
 * Created on 9 avr. 2009, 17:13:13
 */
package gevi.Views.jifGraphs;

import gevi.Views.*;
import gevi.Model.Creneau;
import gevi.Model.Depense;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Singleton;
import gevi.Model.Versement;
import gevi.Model.Visite;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.beans.PropertyVetoException;
import java.text.AttributedString;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author root
 */
public class jifGraphFinancier extends javax.swing.JInternalFrame {

    Document _data;
    Date _debut;
    Date _fin;
    Vector<Visite> _visites;
    Vector<Creneau> _astreintes;
    Vector<Creneau> _creneaux;
    Vector<Executant> _medecins;
    Vector<Versement> _versements;
    Vector<Depense> _frais;
    ChartPanel _panelGlobal;
    ChartPanel _panelSource;
    ChartPanel _panelType;
    ChartPanel _panelVersement;

    /** Creates new form jifPeriodReport */
    public jifGraphFinancier(Document data, Date debut, Date fin) {
        initComponents();
        this.setPreferredSize(new Dimension(640, 480));
        _data = data;

        _visites = new Vector();
        _astreintes = new Vector();
        _medecins = new Vector();
        _versements = new Vector();
        _frais = new Vector();
        _creneaux = new Vector();

        _debut = debut;
        _fin = fin;
        SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
        String titre = "Graphique financier du " + format.format(_debut) + " au " + format.format(_fin);

        this.setTitle(titre);

        JFreeChart chartGlobal = ChartFactory.createPieChart("", null, true, true, false);
        JFreeChart chartVersement = ChartFactory.createPieChart("", null, true, true, false);
        JFreeChart chartSource = ChartFactory.createPieChart("", null, true, true, false);
        JFreeChart chartType = ChartFactory.createPieChart("", null, true, true, false);

        _panelGlobal = new ChartPanel(chartGlobal);
        _panelVersement = new ChartPanel(chartVersement);
        _panelSource = new ChartPanel(chartSource);
        _panelType = new ChartPanel(chartType);

        jpn1.add(_panelGlobal, BorderLayout.CENTER);
        jpn2.add(_panelVersement, BorderLayout.CENTER);
        jpn3.add(_panelSource, BorderLayout.CENTER);
        jpn4.add(_panelType, BorderLayout.CENTER);

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        refresh();
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpn1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jbtImprimer1 = new javax.swing.JButton();
        jpn3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jbtImprimer3 = new javax.swing.JButton();
        jpn2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbtImprimer2 = new javax.swing.JButton();
        jpn4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jbtImprimer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrbCamembert = new javax.swing.JRadioButton();
        jrbBarres = new javax.swing.JRadioButton();
        jckRemplaçants = new javax.swing.JCheckBox();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_bleu.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 480));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jpn1.setLayout(new java.awt.BorderLayout());

        jbtImprimer1.setText("Imprimer");
        jbtImprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimer1ActionPerformed(evt);
            }
        });
        jPanel7.add(jbtImprimer1);

        jpn1.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jpn1);

        jpn3.setLayout(new java.awt.BorderLayout());

        jbtImprimer3.setText("Imprimer");
        jbtImprimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimer3ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtImprimer3);

        jpn3.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jpn3);

        jpn2.setLayout(new java.awt.BorderLayout());

        jbtImprimer2.setText("Imprimer");
        jbtImprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimer2ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtImprimer2);

        jpn2.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jpn2);

        jpn4.setLayout(new java.awt.BorderLayout());

        jbtImprimer.setText("Imprimer");
        jbtImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimerActionPerformed(evt);
            }
        });
        jPanel10.add(jbtImprimer);

        jpn4.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jpn4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        buttonGroup1.add(jrbCamembert);
        jrbCamembert.setSelected(true);
        jrbCamembert.setText("Camembert");
        jrbCamembert.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jrbCamembert.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jrbCamembert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCamembertActionPerformed(evt);
            }
        });
        jPanel4.add(jrbCamembert);

        buttonGroup1.add(jrbBarres);
        jrbBarres.setText("Barres");
        jrbBarres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBarresActionPerformed(evt);
            }
        });
        jPanel4.add(jrbBarres);

        jckRemplaçants.setText("Séparer les remplaçants");
        jckRemplaçants.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jckRemplaçants.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jckRemplaçants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckRemplaçantsActionPerformed(evt);
            }
        });
        jPanel4.add(jckRemplaçants);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimerActionPerformed
        _panelType.createChartPrintJob();
}//GEN-LAST:event_jbtImprimerActionPerformed

    private void jbtImprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimer1ActionPerformed
        _panelGlobal.createChartPrintJob();
    }//GEN-LAST:event_jbtImprimer1ActionPerformed

    private void jbtImprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimer2ActionPerformed
        _panelVersement.createChartPrintJob();
    }//GEN-LAST:event_jbtImprimer2ActionPerformed

    private void jbtImprimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimer3ActionPerformed
        _panelSource.createChartPrintJob();
    }//GEN-LAST:event_jbtImprimer3ActionPerformed

    private void jckRemplaçantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckRemplaçantsActionPerformed
        refresh();
    }//GEN-LAST:event_jckRemplaçantsActionPerformed

    private void jrbCamembertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCamembertActionPerformed
        refresh();
}//GEN-LAST:event_jrbCamembertActionPerformed

    private void jrbBarresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBarresActionPerformed
        refresh();
}//GEN-LAST:event_jrbBarresActionPerformed

    private void refresh() {
        _visites.clear();
        _astreintes.clear();
        _medecins.clear();
        _versements.clear();
        _frais.clear();
        _creneaux.clear();

        Vector<Creneau> cren = Singleton.instance().getDocument().getCreneaux();
        for (int i = 0; i < cren.size(); i++) {
            Creneau c = cren.get(i);
            Vector visites = c.getVisites();
            Date d = c.getDate();
            if ((d.before(_fin) && d.after(_debut)) || (d.equals(_fin)) || (d.equals(_debut))) {
                if (c.getAstreintePayee()) {
                    _astreintes.add(c);
                }

                for (int j = 0; j < c.getVisites().size(); j++) {
                    if (c.getVisites().get(j).getSommePayée() > 0) {
                        _medecins.add(c.getExecutant());
                        _visites.add(c.getVisites().get(j));
                    }
                }

                _creneaux.add(c);
            }
        }

        Vector<Versement> vers = Singleton.instance().getDocument().getVersements();
        for (int i = 0; i < vers.size(); i++) {
            Versement v = vers.get(i);
            Date d = v.getDate();
            if ((d.before(_fin) && d.after(_debut)) || (d.equals(_fin)) || (d.equals(_debut))) {
                _versements.add(v);
            }
        }

        Vector<Depense> deps = Singleton.instance().getDocument().getDepenses();
        for (int i = 0; i < deps.size(); i++) {
            Depense p = deps.get(i);
            Date d = p.getDate();
            if ((d.before(_fin) && d.after(_debut)) || (d.equals(_fin)) || (d.equals(_debut))) {
                _frais.add(p);
            }
        }


        if (jrbBarres.isSelected()) {
            _panelGlobal.setChart(getGlobalChart(jckRemplaçants.isSelected()));
            _panelVersement.setChart(getVersementChart(jckRemplaçants.isSelected()));
            _panelSource.setChart(getSourceChart(jckRemplaçants.isSelected()));
            _panelType.setChart(getTypeChart(jckRemplaçants.isSelected()));
        } else {
            _panelGlobal.setChart(getGlobalPie(jckRemplaçants.isSelected()));
            _panelVersement.setChart(getVersementPie(jckRemplaçants.isSelected()));
            _panelSource.setChart(getSourcePie(jckRemplaçants.isSelected()));
            _panelType.setChart(getTypePie(jckRemplaçants.isSelected()));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtImprimer;
    private javax.swing.JButton jbtImprimer1;
    private javax.swing.JButton jbtImprimer2;
    private javax.swing.JButton jbtImprimer3;
    private javax.swing.JButton jbtOK;
    private javax.swing.JCheckBox jckRemplaçants;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpn4;
    private javax.swing.JRadioButton jrbBarres;
    private javax.swing.JRadioButton jrbCamembert;
    // End of variables declaration//GEN-END:variables

    public JFreeChart getGlobalChart(boolean remplacant) {
        DefaultCategoryDataset ds = new DefaultCategoryDataset();

        double total = 0.0;
        double depenses = 0.0;

        boolean remp = remplacant;
        for (int i = 0; i < _visites.size(); i++) {
            Visite v = _visites.get(i);
            if (remp) {
                if (_medecins.get(i).equals(_data.getUtilisateur())) {
                    total += v.getSommePayée();
                } else {
                    total += v.getSommePayée() * _data.getParametres().getPrelevement();
                }
            } else {
                total += v.getSommePayée();
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            Creneau c = _astreintes.get(i);
            if (remp) {
                if (c.getExecutant().equals(_data.getUtilisateur())) {
                    total += _data.getParametres().getTarifAstreinte();
                }
            } else {
                total += _data.getParametres().getTarifAstreinte();
            }
        }

        for (int i = 0; i < _frais.size(); i++) {
            Depense d = _frais.get(i);
            String nom = d.getCategorie().getNom();
            depenses += d.getMontant();

            if ((d.getMontant() / total) < 0.05) {
                nom = "Autre";
            }

            try {
                double tmp = (Double) ds.getValue("Frais", nom);
                ds.setValue(tmp + d.getMontant(), "Frais", nom);
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = d.getMontant();
                ds.addValue(tmp, "Frais", nom);
            } catch (NullPointerException ex) {
                double tmp = d.getMontant();
                ds.addValue(tmp, "Frais", nom);
            }
        }

        if (!remp) {
            for (int i = 0; i < _versements.size(); i++) {
                Versement v = _versements.get(i);
                Executant e = v.getExecutant();
                String nom = e.getNom() + " " + e.getPrenom();
                depenses += v.getMontant();
                try {
                    double tmp = (Double) ds.getValue("Versements", nom);
                    ds.setValue(tmp + v.getMontant(), "Versements", nom);
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = v.getMontant();
                    ds.addValue(tmp, "Versements", nom);
                } catch (NullPointerException ex) {
                    double tmp = v.getMontant();
                    ds.addValue(tmp, "Versements", nom);
                }
            }

            for (int i = 0; i < _creneaux.size(); i++) {
                Creneau c = _creneaux.get(i);
                Executant e = c.getExecutant();
                String nom = e.getNom() + " " + e.getPrenom();
                if (!e.equals(_data.getUtilisateur())) {
                    if (c.getAstreintePayee() && (c.getVersementId() < 0)) {
                        depenses += _data.getParametres().getTarifAstreinte();
                        try {
                            double tmp = (Double) ds.getValue("Dû", nom);
                            ds.setValue(tmp + _data.getParametres().getTarifAstreinte(), "Dû", nom);
                        } catch (org.jfree.data.UnknownKeyException ex) {
                            double tmp = _data.getParametres().getTarifAstreinte();
                            ds.addValue(tmp, "Dû", nom);
                        } catch (NullPointerException ex) {
                            double tmp = _data.getParametres().getTarifAstreinte();
                            ds.addValue(tmp, "Dû", nom);
                        }
                    }

                    for (int j = 0; j < c.getVisites().size(); j++) {
                        Visite v = c.getVisites().get(j);
                        if (v.getPaye() && (v.getVersementId() < 0)) {
                            depenses += v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                            try {
                                double tmp = (Double) ds.getValue("Dû", nom);
                                ds.setValue(tmp + v.getSommePayée() * (1 - _data.getParametres().getPrelevement()), "Dû", nom);
                            } catch (org.jfree.data.UnknownKeyException ex) {
                                double tmp = v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                                ds.addValue(tmp, "Dû", nom);
                            } catch (NullPointerException ex) {
                                double tmp = v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                                ds.addValue(tmp, "Dû", nom);
                            }
                        }
                    }
                }
            }
        }

        ds.addValue(total - depenses, "Bénéfice", "Bénéfice");

        JFreeChart chart;
        chart = ChartFactory.createStackedBarChart("Global", "Source", "Montant", ds, PlotOrientation.HORIZONTAL, true, true, false);

        BarRenderer renderer = (BarRenderer) chart.getCategoryPlot().getRenderer();
        chart.getCategoryPlot().setBackgroundAlpha(0);

        GradientPaint gp0 = new GradientPaint(
                0.0f, 0.0f, new Color(0, 255, 255),
                0.0f, 0.0f, new Color(0, 64, 64));
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesItemLabelsVisible(0, true);

        GradientPaint gp1 = new GradientPaint(
                0.0f, 0.0f, Color.red,
                0.0f, 0.0f, new Color(64, 0, 0));
        renderer.setSeriesPaint(1, gp1);
        renderer.setSeriesItemLabelsVisible(1, true);

        GradientPaint gp2 = new GradientPaint(
                0.0f, 0.0f, Color.green,
                0.0f, 0.0f, new Color(0, 64, 0));
        renderer.setSeriesPaint(2, gp2);
        renderer.setSeriesItemLabelsVisible(2, true);

        GradientPaint gp3 = new GradientPaint(
                0.0f, 0.0f, Color.blue,
                0.0f, 0.0f, new Color(0, 0, 64));
        renderer.setSeriesPaint(3, gp3);
        renderer.setSeriesItemLabelsVisible(3, true);

        GradientPaint gp4 = new GradientPaint(
                0.0f, 0.0f, Color.yellow,
                0.0f, 0.0f, new Color(64, 64, 0));
        renderer.setSeriesPaint(4, gp4);
        renderer.setSeriesItemLabelsVisible(4, true);


        ItemLabelPosition pos = new ItemLabelPosition(ItemLabelAnchor.CENTER, TextAnchor.CENTER);
        renderer.setBasePositiveItemLabelPosition(pos);
        renderer.setBaseItemLabelGenerator(new CategoryItemLabelGenerator() {

            public String generateRowLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg0.getRowKey(arg1), "")) + " €";
            }

            public String generateColumnLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
            }

            public String generateLabel(
                    CategoryDataset arg0, int arg1, int arg2) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg1, arg2)) + " €";
            }
        });
        return chart;
    }

    public JFreeChart getVersementChart(boolean remplacant) {
        DefaultCategoryDataset ds = new DefaultCategoryDataset();

        for (int i = 0; i < _frais.size(); i++) {

            Depense d = _frais.get(i);
            String nom = d.getCategorie().getNom();

            try {
                double tmp = (Double) ds.getValue("", nom);
                ds.setValue(tmp + d.getMontant(), "", nom);
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = d.getMontant();
                ds.addValue(tmp, "", nom);
            } catch (NullPointerException ex) {
                double tmp = d.getMontant();
                ds.addValue(tmp, "", nom);
            }
        }

        if (!remplacant) {
            for (int i = 0; i < _versements.size(); i++) {
                Versement v = _versements.get(i);
                Executant e = v.getExecutant();
                String nom = e.getNom() + " " + e.getPrenom();
                try {
                    double tmp = (Double) ds.getValue("", nom);
                    ds.setValue(tmp + v.getMontant(), "", nom);
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = v.getMontant();
                    ds.addValue(tmp, "", nom);
                } catch (NullPointerException ex) {
                    double tmp = v.getMontant();
                    ds.addValue(tmp, "", nom);
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createStackedBarChart("Dépenses", "Catégorie", "Montant", ds, PlotOrientation.HORIZONTAL, false, true, false);

        BarRenderer renderer = (BarRenderer) chart.getCategoryPlot().getRenderer();
        chart.getCategoryPlot().setBackgroundAlpha(0);
        GradientPaint gp0 = new GradientPaint(
                0.0f, 0.0f, new Color(255, 0, 0),
                0.0f, 0.0f, new Color(64, 0, 0));
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesItemLabelsVisible(0, true);
        ItemLabelPosition pos = new ItemLabelPosition(ItemLabelAnchor.CENTER, TextAnchor.CENTER);
        renderer.setBasePositiveItemLabelPosition(pos);
        renderer.setBaseItemLabelGenerator(new CategoryItemLabelGenerator() {

            public String generateRowLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg0.getRowKey(arg1), "")) + " €";
            }

            public String generateColumnLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
            }

            public String generateLabel(
                    CategoryDataset arg0, int arg1, int arg2) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg1, arg2)) + " €";
            }
        });
        return chart;
    }

    public JFreeChart getSourceChart(boolean remplacant) {
        DefaultCategoryDataset ds = new DefaultCategoryDataset();

        double percent = 1;
        for (int i = 0; i < _visites.size(); i++) {
            for (int k = 0; k < _visites.get(i).getPayements().size(); k++) {
                String nom = "";
                if (remplacant) {
                    if (_medecins.get(i).equals(_data.getUtilisateur())) {
                        nom = _visites.get(i).getPayements().get(k).getSourcePayement();
                        percent = 1.0;
                    } else {
                        nom = "Remplaçants";
                        percent = _data.getParametres().getPrelevement();
                    }

                } else {
                    nom = _visites.get(i).getPayements().get(k).getSourcePayement();
                    percent = 1.0;
                }
                try {
                    double tmp = (Double) ds.getValue("", nom);
                    ds.setValue(tmp + _visites.get(i).getSommePayée() * percent, "", nom);
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = _visites.get(i).getSommePayée() * percent;
                    ds.addValue(tmp, "", nom);
                } catch (NullPointerException ex) {
                    double tmp = _visites.get(i).getSommePayée() * percent;
                    ds.addValue(tmp, "", nom);
                }
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            String nom = "";
            if (remplacant) {
                if (_astreintes.get(i).getExecutant().equals(_data.getUtilisateur())) {
                    try {
                        double tmp = (Double) ds.getValue("", "Astreintes");
                        ds.setValue(tmp + Singleton.instance().getDocument().getParametres().getTarifAstreinte(), "", "Astreintes");
                    } catch (org.jfree.data.UnknownKeyException ex) {
                        double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                        ds.addValue(tmp, "", "Astreintes");
                    } catch (NullPointerException ex) {
                        double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                        ds.addValue(tmp, "", "Astreintes");
                    }
                }
            } else {
                try {
                    double tmp = (Double) ds.getValue("", "Astreintes");
                    ds.setValue(tmp + Singleton.instance().getDocument().getParametres().getTarifAstreinte(), "", "Astreintes");
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                    ds.addValue(tmp, "", "Astreintes");
                } catch (NullPointerException ex) {
                    double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                    ds.addValue(tmp, "", "Astreintes");
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createStackedBarChart("Revenu par type", "Source", "Montant", ds, PlotOrientation.HORIZONTAL, false, true, false);

        BarRenderer renderer = (BarRenderer) chart.getCategoryPlot().getRenderer();
        chart.getCategoryPlot().setBackgroundAlpha(0);
        GradientPaint gp0 = new GradientPaint(
                0.0f, 0.0f, new Color(255, 255, 0),
                0.0f, 0.0f, new Color(0, 64, 0));
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesItemLabelsVisible(0, true);
        ItemLabelPosition pos = new ItemLabelPosition(ItemLabelAnchor.CENTER, TextAnchor.CENTER);
        renderer.setBasePositiveItemLabelPosition(pos);
        renderer.setBaseItemLabelGenerator(new CategoryItemLabelGenerator() {

            public String generateRowLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg0.getRowKey(arg1), "")) + " €";
            }

            public String generateColumnLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
            }

            public String generateLabel(
                    CategoryDataset arg0, int arg1, int arg2) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg1, arg2)) + " €";
            }
        });
        return chart;
    }

    public JFreeChart getTypeChart(boolean remplacant) {
        DefaultCategoryDataset ds = new DefaultCategoryDataset();

        double percent = 1;
        for (int i = 0; i < _visites.size(); i++) {

            String nom = "";
            if (remplacant) {

                if (_medecins.get(i).equals(_data.getUtilisateur())) {
                    nom = _visites.get(i).getTypeVisite();
                    percent = 1.0;
                } else {
                    nom = "Remplaçants";
                    percent = _data.getParametres().getPrelevement();
                }

            } else {
                nom = _visites.get(i).getTypeVisite();
                percent = 1.0;
            }
            try {
                double tmp = (Double) ds.getValue("", nom);
                ds.setValue(tmp + _visites.get(i).getSommePayée() * percent, "", nom);
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = _visites.get(i).getSommePayée() * percent;
                ds.addValue(tmp, "", nom);
            } catch (NullPointerException ex) {
                double tmp = _visites.get(i).getSommePayée() * percent;
                ds.addValue(tmp, "", nom);
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            String nom = "";
            if (remplacant) {

                if (_astreintes.get(i).getExecutant().equals(_data.getUtilisateur())) {
                    try {
                        double tmp = (Double) ds.getValue("", "Astreintes");
                        ds.setValue(tmp + Singleton.instance().getDocument().getParametres().getTarifAstreinte(), "", "Astreintes");
                    } catch (org.jfree.data.UnknownKeyException ex) {
                        double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                        ds.addValue(tmp, "", "Astreintes");
                    } catch (NullPointerException ex) {
                        double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                        ds.addValue(tmp, "", "Astreintes");
                    }

                }
            } else {
                try {
                    double tmp = (Double) ds.getValue("", "Astreintes");
                    ds.setValue(tmp + Singleton.instance().getDocument().getParametres().getTarifAstreinte(), "", "Astreintes");
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                    ds.addValue(tmp, "", "Astreintes");
                } catch (NullPointerException ex) {
                    double tmp = Singleton.instance().getDocument().getParametres().getTarifAstreinte();
                    ds.addValue(tmp, "", "Astreintes");
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createStackedBarChart("Revenu par type", "Source", "Montant", ds, PlotOrientation.HORIZONTAL, false, true, false);

        BarRenderer renderer = (BarRenderer) chart.getCategoryPlot().getRenderer();
        chart.getCategoryPlot().setBackgroundAlpha(0);
        GradientPaint gp0 = new GradientPaint(
                0.0f, 0.0f, new Color(255, 0, 255),
                0.0f, 0.0f, new Color(64, 0, 64));
        renderer.setSeriesPaint(0, gp0);
        renderer.setSeriesItemLabelsVisible(0, true);
        ItemLabelPosition pos = new ItemLabelPosition(ItemLabelAnchor.CENTER, TextAnchor.CENTER);
        renderer.setBasePositiveItemLabelPosition(pos);
        renderer.setBaseItemLabelGenerator(new CategoryItemLabelGenerator() {

            public String generateRowLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg0.getRowKey(arg1), "")) + " €";
            }

            public String generateColumnLabel(
                    CategoryDataset arg0, int arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
            }

            public String generateLabel(
                    CategoryDataset arg0, int arg1, int arg2) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return df.format((Double) arg0.getValue(arg1, arg2)) + " €";
            }
        });
        return chart;
    }

    public JFreeChart getGlobalPie(boolean remplacant) {
        DefaultPieDataset ds = new DefaultPieDataset();

        double total = 0.0;
        double depenses = 0.0;

        boolean remp = remplacant;
        for (int i = 0; i < _visites.size(); i++) {
            Visite v = _visites.get(i);
            if (remp) {
                if (_medecins.get(i).equals(_data.getUtilisateur())) {
                    total += v.getSommePayée();
                } else {
                    total += v.getSommePayée() * _data.getParametres().getPrelevement();
                }
            } else {
                total += v.getSommePayée();
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            Creneau c = _astreintes.get(i);
            if (remp) {
                if (c.getExecutant().equals(_data.getUtilisateur())) {
                    total += _data.getParametres().getTarifAstreinte();
                }
            } else {
                total += _data.getParametres().getTarifAstreinte();
            }
        }

        for (int i = 0; i < _frais.size(); i++) {
            Depense d = _frais.get(i);
            String nom = d.getCategorie().getNom();
            depenses += d.getMontant();

            if ((d.getMontant() / total) < 0.05) {
                nom = "Autre";
            }

            try {
                double tmp = (Double) ds.getValue(nom);
                ds.setValue(nom, tmp + d.getMontant());
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = d.getMontant();
                ds.setValue(nom, tmp);
            } catch (NullPointerException ex) {
                double tmp = d.getMontant();
                ds.setValue(nom, tmp);
            }
        }

        if (!remp) {
            for (int i = 0; i < _versements.size(); i++) {
                Versement v = _versements.get(i);
                Executant e = v.getExecutant();
                String nom = e.getNom() + " " + e.getPrenom();
                depenses += v.getMontant();
                try {
                    double tmp = (Double) ds.getValue(nom);
                    ds.setValue(nom, tmp);
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = v.getMontant();
                    ds.insertValue(ds.getKeys().size(), nom, (Double) (tmp + v.getMontant()));
                } catch (NullPointerException ex) {
                    double tmp = v.getMontant();
                    ds.insertValue(ds.getKeys().size(), nom, (Double) (tmp + v.getMontant()));
                }
            }

            for (int i = 0; i < _creneaux.size(); i++) {
                Creneau c = _creneaux.get(i);
                Executant e = c.getExecutant();
                if (!e.equals(_data.getUtilisateur())) {
                    if (c.getAstreintePayee() && (c.getVersementId() < 0)) {
                        depenses += _data.getParametres().getTarifAstreinte();
                        try {
                            double tmp = (Double) ds.getValue("Dû");
                            ds.setValue("Dû", tmp + _data.getParametres().getTarifAstreinte());
                        } catch (org.jfree.data.UnknownKeyException ex) {
                            double tmp = _data.getParametres().getTarifAstreinte();
                            ds.insertValue(ds.getKeys().size(), "Dû", tmp);
                        } catch (NullPointerException ex) {
                            double tmp = _data.getParametres().getTarifAstreinte();
                            ds.insertValue(ds.getKeys().size(), "Dû", tmp);
                        }
                    }

                    for (int j = 0; j < c.getVisites().size(); j++) {
                        Visite v = c.getVisites().get(j);
                        if (v.getPaye() && (v.getVersementId() < 0)) {
                            depenses += v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                            try {
                                double tmp = (Double) ds.getValue("Dû");
                                ds.setValue("Dû", tmp + v.getSommePayée() * (1 - _data.getParametres().getPrelevement()));
                            } catch (org.jfree.data.UnknownKeyException ex) {
                                double tmp = v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                                ds.insertValue(ds.getKeys().size(), "Dû", tmp);
                            } catch (NullPointerException ex) {
                                double tmp = v.getSommePayée() * (1 - _data.getParametres().getPrelevement());
                                ds.insertValue(ds.getKeys().size(), "Dû", tmp);
                            }
                        }
                    }
                }
            }
        }

        ds.insertValue(ds.getKeys().size(), "Bénéfice", total - depenses);

        JFreeChart chart;
        chart = ChartFactory.createPieChart("Global", ds, false, true, false);
        chart.getPlot().setBackgroundAlpha(0);
        ((PiePlot) chart.getPlot()).setSimpleLabels(true);
        ((PiePlot) chart.getPlot()).setIgnoreZeroValues(true);
        ((PiePlot) chart.getPlot()).setLabelGenerator(new PieSectionLabelGenerator() {

            public String generateSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return ((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €";
            }

            public AttributedString generateAttributedSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return new AttributedString(((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €");
            }
        });
        return chart;
    }

    public JFreeChart getVersementPie(boolean remplacant) {
        DefaultPieDataset ds = new DefaultPieDataset();

        for (int i = 0; i < _frais.size(); i++) {

            Depense d = _frais.get(i);
            String nom = d.getCategorie().getNom();

            try {
                double tmp = (Double) ds.getValue(nom);
                ds.setValue(nom, tmp + d.getMontant());
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = d.getMontant();
                ds.insertValue(ds.getKeys().size(), nom, tmp);
            } catch (NullPointerException ex) {
                double tmp = d.getMontant();
                ds.insertValue(ds.getKeys().size(), nom, tmp);
            }
        }

        if (!remplacant) {
            for (int i = 0; i < _versements.size(); i++) {
                Versement v = _versements.get(i);
                Executant e = v.getExecutant();
                String nom = e.getNom() + " " + e.getPrenom();
                try {
                    double tmp = (Double) ds.getValue(nom);
                    ds.setValue(nom, tmp + v.getMontant());
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = v.getMontant();
                    ds.insertValue(ds.getKeys().size(), nom, tmp);
                } catch (NullPointerException ex) {
                    double tmp = v.getMontant();
                    ds.insertValue(ds.getKeys().size(), nom, tmp);
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createPieChart("Dépenses", ds, false, true, false);
        chart.getPlot().setBackgroundAlpha(0);
        ((PiePlot) chart.getPlot()).setSimpleLabels(true);
        ((PiePlot) chart.getPlot()).setIgnoreZeroValues(true);
        ((PiePlot) chart.getPlot()).setLabelGenerator(new PieSectionLabelGenerator() {

            public String generateSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return ((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €";
            }

            public AttributedString generateAttributedSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return new AttributedString(((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €");
            }
        });
        return chart;
    }

    public JFreeChart getSourcePie(boolean remplacant) {
        DefaultPieDataset ds = new DefaultPieDataset();

        double percent = 1;
        for (int i = 0; i < _visites.size(); i++) {
            for (int k = 0; k < _visites.get(i).getPayements().size(); k++) {
                String nom = "";
                if (remplacant) {

                    if (_medecins.get(i).equals(_data.getUtilisateur())) {
                        nom = _visites.get(i).getPayements().get(k).getSourcePayement();
                        percent = 1.0;
                    } else {
                        nom = "Remplaçants";
                        percent = _data.getParametres().getPrelevement();
                    }

                } else {
                    nom = _visites.get(i).getPayements().get(k).getSourcePayement();
                    percent = 1.0;
                }
                try {
                    double tmp = (Double) ds.getValue(nom);
                    ds.setValue(nom, tmp + _visites.get(i).getSommePayée() * percent);
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = _visites.get(i).getSommePayée() * percent;
                    ds.insertValue(ds.getKeys().size(), nom, tmp);
                } catch (NullPointerException ex) {
                    double tmp = _visites.get(i).getSommePayée() * percent;
                    ds.insertValue(ds.getKeys().size(), nom, tmp);
                }
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            String nom = "";
            if (remplacant) {
                if (_astreintes.get(i).getExecutant().equals(_data.getUtilisateur())) {
                    try {
                        double tmp = (Double) ds.getValue("Astreintes");
                        ds.setValue("Astreintes", tmp + _data.getParametres().getTarifAstreinte());
                    } catch (org.jfree.data.UnknownKeyException ex) {
                        double tmp = _data.getParametres().getTarifAstreinte();
                        ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                    } catch (NullPointerException ex) {
                        double tmp = _data.getParametres().getTarifAstreinte();
                        ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                    }
                }
            } else {
                try {
                    double tmp = (Double) ds.getValue("Astreintes");
                    ds.setValue("Astreintes", tmp + _data.getParametres().getTarifAstreinte());
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = _data.getParametres().getTarifAstreinte();
                    ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                } catch (NullPointerException ex) {
                    double tmp = _data.getParametres().getTarifAstreinte();
                    ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createPieChart("Sources", ds, false, true, false);
        chart.getPlot().setBackgroundAlpha(0);
        ((PiePlot) chart.getPlot()).setSimpleLabels(true);
        ((PiePlot) chart.getPlot()).setIgnoreZeroValues(true);
        ((PiePlot) chart.getPlot()).setLabelGenerator(new PieSectionLabelGenerator() {

            public String generateSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return ((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €";
            }

            public AttributedString generateAttributedSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return new AttributedString(((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €");
            }
        });
        return chart;
    }

    public JFreeChart getTypePie(boolean remplacant) {
        DefaultPieDataset ds = new DefaultPieDataset();

        double percent = 1;
        for (int i = 0; i < _visites.size(); i++) {

            String nom = "";
            if (remplacant) {

                if (_medecins.get(i).equals(_data.getUtilisateur())) {
                    nom = _visites.get(i).getTypeVisite();
                    percent = 1.0;
                } else {
                    nom = "Remplaçants";
                    percent = _data.getParametres().getPrelevement();
                }

            } else {
                nom = _visites.get(i).getTypeVisite();
                percent = 1.0;
            }
            try {
                double tmp = (Double) ds.getValue(nom);
                ds.setValue(nom, tmp + _visites.get(i).getSommePayée() * percent);
            } catch (org.jfree.data.UnknownKeyException ex) {
                double tmp = _visites.get(i).getSommePayée() * percent;
                ds.insertValue(ds.getKeys().size(), nom, tmp);
            } catch (NullPointerException ex) {
                double tmp = _visites.get(i).getSommePayée() * percent;
                ds.insertValue(ds.getKeys().size(), nom, tmp);
            }
        }

        for (int i = 0; i < _astreintes.size(); i++) {
            String nom = "";
            if (remplacant) {

                if (_astreintes.get(i).getExecutant().equals(_data.getUtilisateur())) {
                    try {
                        double tmp = (Double) ds.getValue("Astreintes");
                        ds.setValue("Astreintes", tmp + _data.getParametres().getTarifAstreinte());
                    } catch (org.jfree.data.UnknownKeyException ex) {
                        double tmp = _data.getParametres().getTarifAstreinte();
                        ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                    } catch (NullPointerException ex) {
                        double tmp = _data.getParametres().getTarifAstreinte();
                        ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                    }

                }
            } else {
                try {
                    double tmp = (Double) ds.getValue("Astreintes");
                    ds.setValue("Astreintes", tmp + _data.getParametres().getTarifAstreinte());
                } catch (org.jfree.data.UnknownKeyException ex) {
                    double tmp = _data.getParametres().getTarifAstreinte();
                    ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                } catch (NullPointerException ex) {
                    double tmp = _data.getParametres().getTarifAstreinte();
                    ds.insertValue(ds.getKeys().size(), "Astreintes", tmp);
                }
            }
        }

        JFreeChart chart;
        chart = ChartFactory.createPieChart("Types", ds, false, true, false);
        chart.getPlot().setBackgroundAlpha(0);
        ((PiePlot) chart.getPlot()).setSimpleLabels(true);
        ((PiePlot) chart.getPlot()).setIgnoreZeroValues(true);
        ((PiePlot) chart.getPlot()).setLabelGenerator(new PieSectionLabelGenerator() {

            public String generateSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return ((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €";
            }

            public AttributedString generateAttributedSectionLabel(PieDataset arg0, Comparable arg1) {
                DecimalFormat df = new DecimalFormat("#,##0.00");
                return new AttributedString(((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €");
            }
        });
        return chart;
    }
}
