/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPeriodReport.java
 *
 * Created on 9 avr. 2009, 17:13:13
 */
package gevi.Views.jifGraphs;

import gevi.Views.*;
import freemarker.template.Configuration;
import freemarker.template.DefaultObjectWrapper;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import gevi.Model.Categorie;
import gevi.Model.Depense;
import gevi.Model.Document;
import gevi.Model.Singleton;
import gevi.Model.Versement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.print.PrinterException;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.net.URISyntaxException;
import java.text.AttributedString;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.UnknownKeyException;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author root
 */
public class jifGraphVersements extends javax.swing.JInternalFrame {

    Document _data;
    Vector<Versement> _versements = new Vector();
    Date _debut;
    Date _fin;
    ChartPanel _chartPanel;

    /** Creates new form jifPeriodReport */
    public jifGraphVersements(Document data, Date debut, Date fin) {
        initComponents();
        this.setPreferredSize(new Dimension(640, 480));
        _data = data;

        _debut = debut;
        _fin = fin;
        SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
        String titre = "Graphique des versements du " + format.format(_debut) + " au " + format.format(_fin);

        this.setTitle(titre);

        _versements = new Vector();

        for (int i = 0; i < _data.getVersements().size(); i++) {
            Versement vers = _data.getVersements().get(i);
            if ((vers.getDate().before(_fin) && vers.getDate().after(_debut)) || vers.getDate().equals(_fin) || vers.getDate().equals(_debut)) {
                _versements.add(vers);
            }
        }


        JFreeChart chart;
        chart = ChartFactory.createBarChart("Versements par remplaçant", "Remplaçant", "Montant", null, PlotOrientation.HORIZONTAL, true, true, false);

        _chartPanel = new ChartPanel(chart, true);

        this.add(_chartPanel, BorderLayout.CENTER);

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        jrbCamembert.setSelected(true);

        refresh();

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtImprimer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jrbCamembert = new javax.swing.JRadioButton();
        jrbBarres = new javax.swing.JRadioButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_cyan.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 480));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        jbtImprimer.setText("Imprimer");
        jbtImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtImprimer);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 1, 1));

        buttonGroup1.add(jrbCamembert);
        jrbCamembert.setSelected(true);
        jrbCamembert.setText("Camembert");
        jrbCamembert.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jrbCamembert.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jrbCamembert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCamembertActionPerformed(evt);
            }
        });
        jPanel2.add(jrbCamembert);

        buttonGroup1.add(jrbBarres);
        jrbBarres.setText("Barres");
        jrbBarres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBarresActionPerformed(evt);
            }
        });
        jPanel2.add(jrbBarres);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimerActionPerformed

        _chartPanel.createChartPrintJob();


}//GEN-LAST:event_jbtImprimerActionPerformed

    private void jrbCamembertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCamembertActionPerformed
        refresh();
}//GEN-LAST:event_jrbCamembertActionPerformed

    private void jrbBarresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBarresActionPerformed
        refresh();
    }//GEN-LAST:event_jrbBarresActionPerformed

    private void refresh() {

        if (jrbBarres.isSelected()) {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            for (int cpt = 0; cpt < _versements.size(); cpt++) {
                double tmp = 0.0;
                Versement v = _versements.get(cpt);
                try {
                    ds.incrementValue(v.getMontant(), "", v.getExecutant().getNom() + " " + v.getExecutant().getPrenom());
                } catch (UnknownKeyException e) {
                    ds.addValue(v.getMontant(), "", v.getExecutant().getNom() + " " + v.getExecutant().getPrenom());
                }
            }

            JFreeChart chart;
            chart = ChartFactory.createBarChart("Versements par remplaçant", "Remplaçant", "Montant", ds, PlotOrientation.HORIZONTAL, false, false, false);

            BarRenderer renderer = (BarRenderer) chart.getCategoryPlot().getRenderer();
            chart.getCategoryPlot().setBackgroundAlpha(0);
            GradientPaint gp0 = new GradientPaint(
                    0.0f, 0.0f, Color.blue,
                    0.0f, 0.0f, new Color(0, 0, 64));
            renderer.setSeriesPaint(0, gp0);
            ItemLabelPosition pos = new ItemLabelPosition(ItemLabelAnchor.CENTER, TextAnchor.CENTER);
            renderer.setBasePositiveItemLabelPosition(pos);
            renderer.setSeriesItemLabelsVisible(0, true);
            renderer.setBaseItemLabelGenerator(new CategoryItemLabelGenerator() {

                public String generateRowLabel(CategoryDataset arg0, int arg1) {
                    DecimalFormat df = new DecimalFormat("#,##0.00");
                    return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
                }

                public String generateColumnLabel(CategoryDataset arg0, int arg1) {
                    DecimalFormat df = new DecimalFormat("#,##0.00");
                    return df.format((Double) arg0.getValue("", arg0.getColumnKey(arg1))) + " €";
                }

                public String generateLabel(CategoryDataset arg0, int arg1, int arg2) {
                    DecimalFormat df = new DecimalFormat("#,##0.00");
                    return df.format((Double) arg0.getValue(arg1, arg2)) + " €";
                }
            });
            _chartPanel.setChart(chart);
        } else {
            DefaultPieDataset ds = new DefaultPieDataset();
            for (int cpt = 0; cpt < _versements.size(); cpt++) {
                Versement v = _versements.get(cpt);
                try {
                    double tmp = (Double) ds.getValue(v.getExecutant().getNom() + " " + v.getExecutant().getPrenom());
                    ds.setValue(v.getExecutant().getNom() + " " + v.getExecutant().getPrenom(), v.getMontant() + tmp);
                } catch (UnknownKeyException e) {
                    ds.insertValue(ds.getKeys().size(), v.getExecutant().getNom() + " " + v.getExecutant().getPrenom(), v.getMontant());
                }

            }

            JFreeChart chart;
            chart = ChartFactory.createPieChart("Versement par remplaçant", ds, true, true, false);
            chart.getPlot().setBackgroundAlpha(0);
            ((PiePlot) chart.getPlot()).setSimpleLabels(true);
            ((PiePlot) chart.getPlot()).setIgnoreZeroValues(true);
            ((PiePlot) chart.getPlot()).setLabelGenerator(new PieSectionLabelGenerator() {

                public String generateSectionLabel(PieDataset arg0, Comparable arg1) {
                    DecimalFormat df = new DecimalFormat("#,##0.00");
                    return ((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €";
                }

                public AttributedString generateAttributedSectionLabel(PieDataset arg0, Comparable arg1) {
                    DecimalFormat df = new DecimalFormat("#,##0.00");
                    return new AttributedString(((String) arg1) + " - " + df.format((Double) arg0.getValue(arg1)) + " €");
                }
            });
            _chartPanel.setChart(chart);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtImprimer;
    private javax.swing.JButton jbtOK;
    private javax.swing.JRadioButton jrbBarres;
    private javax.swing.JRadioButton jrbCamembert;
    // End of variables declaration//GEN-END:variables
}
