/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgNewDocument.java
 *
 * Created on 8 avr. 2009, 15:40:34
 */
package gevi.Views.jdgOptions;

import gevi.Model.Document;
import gevi.Model.Singleton;
import gevi.Model.Utilisateur;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class jdgViewUser extends javax.swing.JDialog {

    Document _doc;

    /** Creates new form jdgNewDocument */
    public jdgViewUser(java.awt.Frame parent, boolean modal,Document doc) {
        super(parent, modal);
        initComponents();

        _doc=doc;

        Utilisateur user = _doc.getUtilisateur();
        jtaAdresse.setText(user.getAdresse());
        jtfCourriel.setText(user.getCourriel());
        jtaDivers.setText(user.getDivers());
        jtfNom.setText(user.getNom());
        jtfPrenom.setText(user.getPrenom());
        jtfTelephone.setText(user.getTelephone());
        jtfADELI.setText(user.getAdeli());

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_bleu.png")).getImage());

        jxdpDate.setDate(doc.getDate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfTelephone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNom = new javax.swing.JTextField();
        jtfPrenom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAdresse = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDivers = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jtfCourriel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfADELI = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau Document");
        setMinimumSize(new java.awt.Dimension(280, 380));

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilisateur"));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Téléphone :");
        jLabel1.setFocusable(false);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));
        jPanel3.add(jtfTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nom :");
        jLabel3.setFocusable(false);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Prénom :");
        jLabel4.setFocusable(false);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Adresse :");
        jLabel5.setFocusable(false);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));
        jPanel3.add(jtfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 20));
        jPanel3.add(jtfPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 20));

        jtaAdresse.setColumns(20);
        jtaAdresse.setRows(4);
        jScrollPane1.setViewportView(jtaAdresse);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, 80));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Divers :");
        jLabel6.setFocusable(false);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 20));

        jtaDivers.setColumns(20);
        jtaDivers.setRows(4);
        jScrollPane2.setViewportView(jtaDivers);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 190, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Courriel :");
        jLabel2.setFocusable(false);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));
        jPanel3.add(jtfCourriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("n° ADELI");
        jLabel7.setFocusable(false);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 20));
        jPanel3.add(jtfADELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 190, 20));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Début de la période"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jxdpDate.setEditable(false);
        jPanel2.add(jxdpDate, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        Utilisateur user = new Utilisateur();
        user.setAddress(jtaAdresse.getText());
        user.setCourriel(jtfCourriel.getText());
        user.setDivers(jtaDivers.getText());
        user.setNom(jtfNom.getText());
        user.setPrenom(jtfPrenom.getText());
        user.setTelephone(jtfTelephone.getText());
        user.setAdeli(jtfADELI.getText());

        if (user.getNom().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ NOM est vide", "Champ manquant", JOptionPane.ERROR_MESSAGE);
        } else {
            _doc.setUtilisateur(user);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtOK;
    private javax.swing.JTextArea jtaAdresse;
    private javax.swing.JTextArea jtaDivers;
    private javax.swing.JTextField jtfADELI;
    private javax.swing.JTextField jtfCourriel;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfPrenom;
    private javax.swing.JTextField jtfTelephone;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    // End of variables declaration//GEN-END:variables
}
