/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgSaisie.java
 *
 * Created on 7 avr. 2009, 18:11:54
 */
package gevi.Views;

import gevi.Model.Creneau;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Versement;
import gevi.Model.Visite;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class jdgAddVersement extends javax.swing.JDialog {

    Document _document;
    Executant _executant;
    Vector<Object> _operations;
    Vector<Boolean> _reverser;
    double _total = 0;
    double _versement = 0;
    Date _date = new Date();

    /** Creates new form jdgSaisie */
    public jdgAddVersement(java.awt.Frame parent, boolean modal, Document document, Executant exec) {
        super(parent, modal);
        initComponents();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }
        _document = document;
        _executant = exec;
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_cyan.png")).getImage());

        _operations = new Vector();
        _reverser = new Vector();
        for (int i = 0; i < _document.getCreneaux().size(); i++) {
            Creneau c = _document.getCreneaux().get(i);
            if (c.getExecutant().equals(_executant)) {
                if (c.getAstreinte() && c.getAstreintePayee() && (c.getVersementId() < 0)) {
                    if (c.getVersementId() == -1) {
                        _operations.add(c);
                        _reverser.add(false);
                    }
                }

                for (int j = 0; j < c.getVisites().size(); j++) {
                    Visite v = c.getVisites().get(j);
                    if (v.getPaye() && (v.getVersementId() < 0)) {
                        _operations.add(v);
                        _reverser.add(false);
                    }
                }
            }
        }

        jxdpDate.setDate(new Date());

        mtOperationSelect model = new mtOperationSelect(_operations, _reverser);
        jxtOperations.setModel(model);
        jxtOperations.setDefaultRenderer(String.class, model);
        jxtOperations.setDefaultRenderer(Double.class, model);
        jxtOperations.setDefaultRenderer(Integer.class, model);

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtOperations = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jftfSomme = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftfVersement = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jtfDivers = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Versement");
        setMinimumSize(new java.awt.Dimension(550, 320));
        setModal(true);
        setResizable(false);

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opérations"));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 230));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout(2, 2));

        jxtOperations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jxtOperations.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jxtOperations.setAutoscrolls(false);
        jxtOperations.setColumnSelectionAllowed(true);
        jxtOperations.setSortable(false);
        jxtOperations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jxtOperationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jxtOperations);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Montant des visites :");
        jPanel2.add(jLabel3);

        jftfSomme.setEditable(false);
        jftfSomme.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jftfSomme);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Montant du versement :");
        jPanel2.add(jLabel4);

        jftfVersement.setEditable(false);
        jftfVersement.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jftfVersement);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1, 1, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Date:");
        jPanel4.add(jLabel1);

        jxdpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpDateActionPerformed(evt);
            }
        });
        jPanel4.add(jxdpDate);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Divers :");
        jPanel4.add(jLabel2);
        jPanel4.add(jtfDivers);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        if (jxdpDate.getDate()==null)
        {
            JOptionPane.showMessageDialog(this, "Il n'y a pas de date de payement définie.", "Champ manquant", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (_versement<=0)
        {
            JOptionPane.showMessageDialog(this, "Aucun montant de versement n'est défini", "Champ manquant", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Versement v = new Versement();
        v.setExecutant(_executant);
        int id = -1;
        for (int i = 0; i < _document.getVersements().size(); i++) {
            Versement tmp = _document.getVersements().get(i);
            id = Math.max(tmp.getId(), id);
        }
        id = id + 1;
        v.setId(id);
        v.setMontant(_versement);
        v.setDate(_date);
        v.setDivers(jtfDivers.getText());


        for (int i = 0; i < _reverser.size(); i++) {
            if (_reverser.get(i)) {
                Object obj = _operations.get(i);
                if (obj instanceof Creneau) {
                    ((Creneau) obj).setVersementId(id);
                }
                if (obj instanceof Visite) {
                    ((Visite) obj).setVersementId(id);
                }
            }
        }

        _document.getVersements().add(v);

        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jxtOperationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jxtOperationsMouseClicked
        int i = jxtOperations.getSelectedRow();
        _reverser.set(i, !_reverser.get(i));
        repaint();
    }//GEN-LAST:event_jxtOperationsMouseClicked

    private void jxdpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpDateActionPerformed
        _date=jxdpDate.getDate();
    }//GEN-LAST:event_jxdpDateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtOK;
    private javax.swing.JFormattedTextField jftfSomme;
    private javax.swing.JFormattedTextField jftfVersement;
    private javax.swing.JTextField jtfDivers;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    private org.jdesktop.swingx.JXTable jxtOperations;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        _total = 0;
        _versement = 0;
        for (int i = 0; i < _reverser.size(); i++) {
            if (_reverser.get(i).equals(Boolean.TRUE)) {
                Object obj = _operations.get(i);
                if (obj instanceof Creneau) {
                    Creneau c = (Creneau) obj;
                    if (c.getAstreinte() && c.getAstreintePayee()) {
                        _versement = _versement + _document.getParametres().getTarifAstreinte();
                        _total = _total + _document.getParametres().getTarifAstreinte();
                    }
                }

                if (obj instanceof Visite) {
                    Visite v = (Visite) obj;
                    if (v.getPaye() && (v.getVersementId() < 0)) {
                        _versement = _versement + (1 - _document.getParametres().getPrelevement()) * v.getTotal();
                        _total = _total + v.getTotal();
                    }
                }
            }
        }

        jftfSomme.setValue(_total);
        jftfVersement.setValue(_versement);
    }
}
