/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgSaisie.java
 *
 * Created on 7 avr. 2009, 18:11:54
 */

package gevi.Views;

import gevi.Model.Document;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.ListSelectionModel;

/**
 *
 * @author root
 */
public class jdgBilan extends javax.swing.JDialog {

    Document _document;
    
    /** Creates new form jdgSaisie */
    public jdgBilan(java.awt.Frame parent, boolean modal,Document document) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        _document=document;
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_cyan.png")).getImage());

        mtBilanVersement tableModel = new mtBilanVersement(_document);
        jxtBilan.setModel(tableModel);
        jxtBilan.setDefaultRenderer(String.class, tableModel);
        jxtBilan.setDefaultRenderer(Double.class, tableModel);
        jxtBilan.setDefaultRenderer(Integer.class, tableModel);
        jxtBilan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jxtBilan.getColumn(0).setMinWidth(120);
        
        
        pack();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtBilan = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jbtVoir = new javax.swing.JButton();
        jbtAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Versement");
        setMinimumSize(new java.awt.Dimension(550, 320));
        setModal(true);
        setResizable(false);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bilan"));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 230));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jxtBilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jxtBilan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jxtBilan.setAutoscrolls(false);
        jxtBilan.setColumnSelectionAllowed(true);
        jxtBilan.setEditable(false);
        jxtBilan.setRowSelectionAllowed(false);
        jxtBilan.setSortable(false);
        jScrollPane1.setViewportView(jxtBilan);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtVoir.setText("Voir les versements");
        jbtVoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtVoir);

        jbtAdd.setText("Ajouter un versement");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAdd);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoirActionPerformed
        jdgVersements jdg=new jdgVersements(MainWindow.getMainWindow(), true, _document);
        jdg.setVisible(true);
}//GEN-LAST:event_jbtVoirActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        int sel=jxtBilan.getSelectedColumn();
        if (sel>0)
        {
        jdgAddVersement jdg=new jdgAddVersement(MainWindow.getMainWindow(), true, _document,_document.getRemplacants().get(sel-1));
        jdg.setVisible(true);
        }
        repaint();
    }//GEN-LAST:event_jbtAddActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtVoir;
    private org.jdesktop.swingx.JXTable jxtBilan;
    // End of variables declaration//GEN-END:variables

}
