/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgRemplacant.java
 *
 * Created on 8 avr. 2009, 14:14:46
 */
package gevi.Views;

import gevi.Model.Categorie;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Payement;
import gevi.Model.Visite;
import java.awt.DisplayMode;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author root
 */
public class jdgPayements extends javax.swing.JDialog {

    Visite _data;

    /** Creates new form jdgRemplacant */
    public jdgPayements(java.awt.Frame parent, boolean modal, Visite data) {
        super(parent, modal);

        setPreferredSize(new java.awt.Dimension(527, 200));

        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_vert.png")).getImage());
        _data = data;

        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtAjouter = new javax.swing.JButton();
        jbtSupprimer = new javax.swing.JButton();
        jbtModifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtPayements = new org.jdesktop.swingx.JXTable();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jbtOK.setActionCommand("OK");
        jbtOK.setLabel("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des payements"));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jbtAjouter.setText("Ajouter");
        jbtAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAjouterActionPerformed(evt);
            }
        });

        jbtSupprimer.setText("Supprimer");
        jbtSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSupprimerActionPerformed(evt);
            }
        });

        jbtModifier.setText("Modifier");
        jbtModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtSupprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtModifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jbtAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtModifier)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jxtPayements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jxtPayements);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAjouterActionPerformed

        Payement p=new Payement();
        jdgPayement jdg=new jdgPayement(MainWindow.getMainWindow(),true,p,_data.getTypeVisite());
        jdg.setVisible(true);

        if (p.getMontant()>=0)
        {
            _data.getPayements().add(p);
        }
        repaint();
    }//GEN-LAST:event_jbtAjouterActionPerformed

    private void jbtSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSupprimerActionPerformed

        int sel = jxtPayements.getSelectedRow();
        if (sel>=0)
        {
            _data.getPayements().remove(sel);
        }
        repaint();

    }//GEN-LAST:event_jbtSupprimerActionPerformed

    private void jbtModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifierActionPerformed

        int sel = jxtPayements.getSelectedRow();
        if (sel >= 0) {
           jdgPayement jdg=new jdgPayement(MainWindow.getMainWindow(),true,_data.getPayements().get(sel),_data.getTypeVisite());
           jdg.setVisible(true);
           jdg=null;
        }
        repaint();
    }//GEN-LAST:event_jbtModifierActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAjouter;
    private javax.swing.JButton jbtModifier;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtSupprimer;
    private org.jdesktop.swingx.JXTable jxtPayements;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        mtPayements tableModel = new mtPayements(_data.getPayements());
        jxtPayements.setModel(tableModel);
        jxtPayements.setDefaultRenderer(String.class, tableModel);
        jxtPayements.setDefaultRenderer(Double.class, tableModel);
        jxtPayements.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jxtPayements.setModel(tableModel);
    }
}
