/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCreneau.java
 *
 * Created on 9 avr. 2009, 15:02:03
 */
package gevi.Views;

import gevi.Model.Categorie;
import gevi.Model.Creneau;
import gevi.Model.Depense;
import gevi.Model.Visite;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Singleton;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author root
 */
public class jifComptes extends javax.swing.JInternalFrame {

    Document _data;    
    Date _debut;
    Date _fin;

    /** Creates new form jifCreneau */
    public jifComptes(Document data, Date debut, Date fin) {
        initComponents();
        _data = data;

        SimpleDateFormat f = new SimpleDateFormat("EEEEEEEEE dd MMMMMMMMMMM yyyy");
        this.setTitle("Tenue des compte du " + f.format(debut) + " au " + f.format(fin));

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


        _debut = debut;
        _fin = fin;

        jlbBanquePrecedent.setText("Solde de banque avant le "+f.format(_debut));
        jlbBanqueCourant.setText("Solde de banque le "+f.format(_fin));
        jlbCaissePrecedent.setText("Solde de caisse avant le "+f.format(_debut));
        jlbCaisseCourant.setText("Solde de caisse le "+f.format(_fin));


        repaint();
       

    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtb = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlbBanquePrecedent = new javax.swing.JLabel();
        jftSoldeBanquePrécédent = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbBanqueCourant = new javax.swing.JLabel();
        jftSoldeBanqueCourant = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtbBanque = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlbCaissePrecedent = new javax.swing.JLabel();
        jftSoldeCaisseInitial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jlbCaisseCourant = new javax.swing.JLabel();
        jftSoldeCaisseCourant = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxtbCaisse = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jbtTransfert = new javax.swing.JButton();
        jbtDépense = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_rose.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel6.setLayout(new java.awt.GridLayout());

        jlbBanquePrecedent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbBanquePrecedent.setText("Solde précédent :");
        jPanel6.add(jlbBanquePrecedent);

        jftSoldeBanquePrécédent.setEditable(false);
        jftSoldeBanquePrécédent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel6.add(jftSoldeBanquePrécédent);
        jPanel6.add(jLabel2);

        jlbBanqueCourant.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbBanqueCourant.setText("Solde courant :");
        jPanel6.add(jlbBanqueCourant);

        jftSoldeBanqueCourant.setEditable(false);
        jftSoldeBanqueCourant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel6.add(jftSoldeBanqueCourant);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jxtbBanque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jxtbBanque);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jtb.addTab("Banque", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout());

        jlbCaissePrecedent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbCaissePrecedent.setText("Solde précédent :");
        jPanel7.add(jlbCaissePrecedent);

        jftSoldeCaisseInitial.setEditable(false);
        jftSoldeCaisseInitial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel7.add(jftSoldeCaisseInitial);
        jPanel7.add(jLabel3);

        jlbCaisseCourant.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbCaisseCourant.setText("Solde courant :");
        jPanel7.add(jlbCaisseCourant);

        jftSoldeCaisseCourant.setEditable(false);
        jftSoldeCaisseCourant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel7.add(jftSoldeCaisseCourant);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jxtbCaisse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jxtbCaisse);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jtb.addTab("Caisse", jPanel5);

        jPanel2.add(jtb, java.awt.BorderLayout.CENTER);
        jtb.getAccessibleContext().setAccessibleName("Banque");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jbtTransfert.setText("Ajouter Transfert");
        jbtTransfert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTransfertActionPerformed(evt);
            }
        });
        jPanel1.add(jbtTransfert);

        jbtDépense.setLabel("Ajouter Dépense");
        jbtDépense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDépenseActionPerformed(evt);
            }
        });
        jPanel1.add(jbtDépense);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        MainWindow.getMainWindow().closeWindow(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jbtTransfertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTransfertActionPerformed
        jdgTransfert trans=new jdgTransfert(MainWindow.getMainWindow(), true, _data);
        trans.setVisible(true);
        repaint();
    }//GEN-LAST:event_jbtTransfertActionPerformed

    private void jbtDépenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDépenseActionPerformed
        jdgDepense depense=new jdgDepense(MainWindow.getMainWindow(), true, _data);
        depense.setVisible(true);
        repaint();
}//GEN-LAST:event_jbtDépenseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtDépense;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtTransfert;
    private javax.swing.JFormattedTextField jftSoldeBanqueCourant;
    private javax.swing.JFormattedTextField jftSoldeBanquePrécédent;
    private javax.swing.JFormattedTextField jftSoldeCaisseCourant;
    private javax.swing.JFormattedTextField jftSoldeCaisseInitial;
    private javax.swing.JLabel jlbBanqueCourant;
    private javax.swing.JLabel jlbBanquePrecedent;
    private javax.swing.JLabel jlbCaisseCourant;
    private javax.swing.JLabel jlbCaissePrecedent;
    private javax.swing.JTabbedPane jtb;
    private org.jdesktop.swingx.JXTable jxtbBanque;
    private org.jdesktop.swingx.JXTable jxtbCaisse;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        mtComptes model = new mtComptes(_data, _debut,_fin,true);
        jxtbBanque.setModel(model);
        jxtbBanque.setDefaultRenderer(String.class, model);
        jxtbBanque.setDefaultRenderer(Double.class, model);
        jxtbBanque.setDefaultRenderer(Integer.class, model);
        jxtbBanque.setDefaultRenderer(Date.class, model);

        mtComptes model2 = new mtComptes(_data, _debut,_fin,false);
        jxtbCaisse.setModel(model2);
        jxtbCaisse.setDefaultRenderer(String.class, model2);
        jxtbCaisse.setDefaultRenderer(Double.class, model2);
        jxtbCaisse.setDefaultRenderer(Integer.class, model2);
        jxtbCaisse.setDefaultRenderer(Date.class, model2);

        jftSoldeBanqueCourant.setValue(_data.getBanque().getSoldeBanque(_fin, _data));
        jftSoldeBanquePrécédent.setValue(_data.getBanque().getSoldeBanqueAvant(_debut, _data));

        jftSoldeCaisseCourant.setValue(_data.getBanque().getSoldeCash(_fin, _data));
        jftSoldeCaisseInitial.setValue(_data.getBanque().getSoldeCashAvant(_debut, _data));
    }
}
