/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jpnCreneau.java
 *
 * Created on 9 avr. 2009, 15:34:59
 */
package gevi.Views;

import gevi.Model.Creneau;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Visite;
import java.awt.Graphics;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author root
 */
public class jpnCreneau extends javax.swing.JPanel {

    Creneau _data;
    Document _document;

    /** Creates new form jpnCreneau */
    public jpnCreneau(Creneau data, Document document) {
        initComponents();
        _data = data;
        _document = document;

        mtVisites tableModel = new mtVisites(_data);

        jxtVisites.setModel(tableModel);
        jxtVisites.setDefaultRenderer(Date.class, tableModel);
        jxtVisites.setDefaultRenderer(String.class, tableModel);
        jxtVisites.setDefaultRenderer(Double.class, tableModel);
        jxtVisites.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        String noms[] = new String[_document.getRemplacants().size() + 2];
        noms[0] = _document.getUtilisateur().getNom() + ", " + _document.getUtilisateur().getPrenom();
        noms[1] = "---------------------------------------";
        for (int i = 0; i < _document.getRemplacants().size(); i++) {
            Executant user = (Executant) _document.getRemplacants().get(i);
            noms[i + 2] = user.getNom() + ", " + user.getPrenom() + " (Remplaçant)";
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(noms);
        jcbMedecins.setModel(model);

        if (_data.getExecutant().getNom().equals(""))
        {
            _data.setExecutant(_document.getUtilisateur());
        }
        else
        {
            if (_data.getExecutant().equals(_document.getUtilisateur()))
            {
                jcbMedecins.setSelectedItem(_data.getExecutant().getNom()+", "+_data.getExecutant().getPrenom());
            }
            else
            {
                jcbMedecins.setSelectedItem(_data.getExecutant().getNom()+", "+_data.getExecutant().getPrenom()+" (Remplaçant)");
            }
        }

        jxdpDate.setDate(_data.getDate());
        if (_data.getDatePayementAstreinte() != null) {
            jxdpDatePayementAstreinte.setDate(_data.getDatePayementAstreinte());
        }
        jcbAstreintePayee.setSelected(_data.getAstreintePayee());

        refreshCombo();
        jxdpDate.setFormats(new String[]{"EEEEEEEEE dd MMMMMMMMMMM yyyy"});
        jxdpDatePayementAstreinte.setFormats(new String[]{"EEEEEEEEE dd MMMMMMMMMMM yyyy"});

        jspKilometres.getModel().setValue(_data.getKilometres());

        repaint();
    }

    private void refreshCombo() {
        Executant user = _data.getExecutant();

        if (user == _document.getUtilisateur()) {
            jcbMedecins.setSelectedIndex(0);
        } else {
            for (int i = 0; i < _document.getRemplacants().size(); i++) {
                Executant exec = (Executant) _document.getRemplacants().get(i);
                if (user == exec) {
                    jcbMedecins.setSelectedIndex(i + 2);
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnNorth = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jcbMedecins = new javax.swing.JComboBox();
        jcbAstreinte = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jcbAstreintePayee = new javax.swing.JCheckBox();
        jxdpDatePayementAstreinte = new org.jdesktop.swingx.JXDatePicker();
        jLabel20 = new javax.swing.JLabel();
        jspKilometres = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jftfNombreVisites = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jftfTotalVisites = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jftfPaye = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jftfImpaye = new javax.swing.JFormattedTextField();
        jpnCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtEditer = new javax.swing.JButton();
        jbtSupprimer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jxtVisites = new org.jdesktop.swingx.JXTable();

        setPreferredSize(new java.awt.Dimension(705, 309));
        setLayout(new java.awt.BorderLayout());

        jpnNorth.setLayout(new java.awt.GridLayout(1, 2, 1, 1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Créneau"));
        jPanel6.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Date de début du créneau horaire :");
        jPanel6.add(jLabel1);

        jxdpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpDateActionPerformed(evt);
            }
        });
        jPanel6.add(jxdpDate);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Nom du médecin :");
        jPanel6.add(jLabel4);

        jcbMedecins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMedecins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMedecinsActionPerformed(evt);
            }
        });
        jPanel6.add(jcbMedecins);

        jcbAstreinte.setText("Astreinte");
        jcbAstreinte.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jcbAstreinte.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jcbAstreinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAstreinteActionPerformed(evt);
            }
        });
        jPanel6.add(jcbAstreinte);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel6.add(jLabel18);

        jcbAstreintePayee.setText("Astreinte payée");
        jcbAstreintePayee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jcbAstreintePayee.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jcbAstreintePayee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAstreintePayeeActionPerformed(evt);
            }
        });
        jPanel6.add(jcbAstreintePayee);

        jxdpDatePayementAstreinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpDatePayementAstreinteActionPerformed(evt);
            }
        });
        jPanel6.add(jxdpDatePayementAstreinte);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Nombre de kilomètres :");
        jPanel6.add(jLabel20);

        jspKilometres.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jspKilometres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jspKilometresMouseClicked(evt);
            }
        });
        jspKilometres.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jspKilometresPropertyChange(evt);
            }
        });
        jPanel6.add(jspKilometres);

        jpnNorth.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Résumé"));
        jPanel7.setLayout(new java.awt.GridLayout(4, 2, 1, 1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Nombre de visites :");
        jPanel7.add(jLabel15);

        jftfNombreVisites.setEditable(false);
        jftfNombreVisites.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jPanel7.add(jftfNombreVisites);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Total des visites :");
        jPanel7.add(jLabel16);

        jftfTotalVisites.setEditable(false);
        jftfTotalVisites.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel7.add(jftfTotalVisites);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Total payé :");
        jPanel7.add(jLabel19);

        jftfPaye.setEditable(false);
        jftfPaye.setForeground(new java.awt.Color(0, 153, 0));
        jftfPaye.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel7.add(jftfPaye);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Total impayé :");
        jPanel7.add(jLabel21);

        jftfImpaye.setEditable(false);
        jftfImpaye.setForeground(java.awt.Color.red);
        jftfImpaye.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel7.add(jftfImpaye);

        jpnNorth.add(jPanel7);

        add(jpnNorth, java.awt.BorderLayout.NORTH);

        jpnCenter.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 1, 1));

        jbtAdd.setText("Ajouter une visite");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAdd);

        jbtEditer.setText("Editer une visite");
        jbtEditer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditerActionPerformed(evt);
            }
        });
        jPanel2.add(jbtEditer);

        jbtSupprimer.setText("Supprimer une visite");
        jbtSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(jbtSupprimer);
        jPanel2.add(jPanel4);
        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jpnCenter.add(jPanel1, java.awt.BorderLayout.WEST);

        jxtVisites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jxtVisites);

        jpnCenter.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(jpnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        jdgSaisieVisite visite = new jdgSaisieVisite(MainWindow.getMainWindow(), true, this._data);
        visite.setVisible(true);
        repaint();
        visite=null;
}//GEN-LAST:event_jbtAddActionPerformed

    private void jxdpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpDateActionPerformed
        _data.setDate(jxdpDate.getDate());

        SimpleDateFormat format = new SimpleDateFormat("EEEEEEEEE");
        String tmp = format.format(_data.getDate());
        if (tmp.equals("samedi") || tmp.equals("dimanche")) {
            _data.setAstreinte(true);
        }
        repaint();
    }//GEN-LAST:event_jxdpDateActionPerformed

    private void jcbMedecinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMedecinsActionPerformed
        int index = jcbMedecins.getSelectedIndex();

        if (index == 0) {
            _data.setExecutant(_document.getUtilisateur());
        } else {
            if (index == 1) {
                refreshCombo();
            } else {
                _data.setExecutant((Executant) _document.getRemplacants().get(index - 2));
            }
        }
    }//GEN-LAST:event_jcbMedecinsActionPerformed

    private void jbtEditerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditerActionPerformed
        if (jxtVisites.getSelectedRow() >= 0) {
            jdgSaisieVisite visite = new jdgSaisieVisite(MainWindow.getMainWindow(), true, this._data, (Visite) _data.getVisites().get(jxtVisites.getSelectedRow()));
            visite.setVisible(true);
            repaint();
            visite=null;
        }
}//GEN-LAST:event_jbtEditerActionPerformed

    private void jbtSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSupprimerActionPerformed
        if (jxtVisites.getSelectedRow() >= 0) {
            _data.getVisites().remove(jxtVisites.getSelectedRow());
            repaint();
        }
    }//GEN-LAST:event_jbtSupprimerActionPerformed

    private void jcbAstreinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAstreinteActionPerformed

        _data.setAstreinte(jcbAstreinte.isSelected());
        repaint();
    }//GEN-LAST:event_jcbAstreinteActionPerformed

    private void jcbAstreintePayeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAstreintePayeeActionPerformed

        if (_data.getAstreintePayee() && _data.getVersementId() >= 0) {
            jcbAstreintePayee.setSelected(true);
            JOptionPane.showMessageDialog(this, "L'astreinte a déjà été reversée, il est impossible d'annuler le payement.", "Impossible", JOptionPane.ERROR_MESSAGE);
        } else {
            _data.setAstreintePayee(jcbAstreintePayee.isSelected());
        }
        repaint();
}//GEN-LAST:event_jcbAstreintePayeeActionPerformed

    private void jxdpDatePayementAstreinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpDatePayementAstreinteActionPerformed
        _data.setDatePayementAstreinte(jxdpDatePayementAstreinte.getDate());
}//GEN-LAST:event_jxdpDatePayementAstreinteActionPerformed

    private void jspKilometresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jspKilometresPropertyChange
        _data.setKilometres((Integer)jspKilometres.getModel().getValue());
    }//GEN-LAST:event_jspKilometresPropertyChange

    private void jspKilometresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jspKilometresMouseClicked
        _data.setKilometres((Integer)jspKilometres.getModel().getValue());
    }//GEN-LAST:event_jspKilometresMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtEditer;
    private javax.swing.JButton jbtSupprimer;
    private javax.swing.JCheckBox jcbAstreinte;
    private javax.swing.JCheckBox jcbAstreintePayee;
    private javax.swing.JComboBox jcbMedecins;
    private javax.swing.JFormattedTextField jftfImpaye;
    private javax.swing.JFormattedTextField jftfNombreVisites;
    private javax.swing.JFormattedTextField jftfPaye;
    private javax.swing.JFormattedTextField jftfTotalVisites;
    private javax.swing.JPanel jpnCenter;
    private javax.swing.JPanel jpnNorth;
    private javax.swing.JSpinner jspKilometres;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    private org.jdesktop.swingx.JXDatePicker jxdpDatePayementAstreinte;
    private org.jdesktop.swingx.JXTable jxtVisites;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        System.gc();
        System.gc();

        jftfNombreVisites.setValue(Integer.valueOf(_data.getVisites().size()));
        jftfPaye.setValue(Double.valueOf(_data.getTotalPaye()));
        jftfImpaye.setValue(Double.valueOf(_data.getTotalImpaye()));
        jftfTotalVisites.setValue(Double.valueOf(_data.getTotal()));

        jcbAstreinte.setSelected(_data.getAstreinte());
    }
}
