/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPeriodReport.java
 *
 * Created on 9 avr. 2009, 17:13:13
 */
package gevi.Views.jifReports;

import freemarker.template.Configuration;
import freemarker.template.DefaultObjectWrapper;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import gevi.Model.Creneau;
import gevi.Views.*;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Singleton;
import gevi.Views.jifGraphs.jifGraphActivite;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import org.jfree.chart.encoders.KeypointPNGEncoderAdapter;

/**
 *
 * @author root
 */
public class jifReportActivite extends javax.swing.JInternalFrame {

    Document _data;
    Date _debut;
    Date _fin;

    /** Creates new form jifPeriodReport */
    public jifReportActivite(Document data, Date debut, Date fin) {
        initComponents();
        this.setPreferredSize(new Dimension(640, 480));
        _data = data;
        _debut = debut;
        _fin = fin;

        SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
        String titre = "Rapport d'activités du " + format.format(_debut) + " au " + format.format(_fin);
        this.setTitle(titre);

        try {
            jepHTML.setContentType("html");
            File f = genererRapport();
            jepHTML.setPage(f.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(MainWindow.getMainWindow(), e.getLocalizedMessage());
        }

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtImprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepHTML = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jcbRemplacants = new javax.swing.JCheckBox();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_bleu.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 480));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        jbtImprimer.setText("Imprimer");
        jbtImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtImprimer);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jepHTML.setContentType("text/html");
        jepHTML.setEditable(false);
        jScrollPane1.setViewportView(jepHTML);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jcbRemplacants.setText("Inclure les remplaçants");
        jcbRemplacants.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jcbRemplacants.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jcbRemplacants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRemplacantsActionPerformed(evt);
            }
        });
        jPanel2.add(jcbRemplacants);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimerActionPerformed
        try {
            jepHTML.print();

        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(MainWindow.getMainWindow(), e.getLocalizedMessage());
        }
}//GEN-LAST:event_jbtImprimerActionPerformed

    private void jcbRemplacantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRemplacantsActionPerformed
        try {
            jepHTML.setContentType("html");
            File f = genererRapport();
            jepHTML.setPage(f.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(MainWindow.getMainWindow(), e.getLocalizedMessage());
        }
}//GEN-LAST:event_jcbRemplacantsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtImprimer;
    private javax.swing.JButton jbtOK;
    private javax.swing.JCheckBox jcbRemplacants;
    private javax.swing.JEditorPane jepHTML;
    // End of variables declaration//GEN-END:variables

    public File genererRapport() {
        File address = null;

        try {
            Configuration cfg = new Configuration();
            URI uri=getClass().getResource("/gevi/templates").toURI();
            if (uri.toString().contains(".jar!"))
            {
                String tmp=uri.toString();
                tmp=tmp.substring(10, tmp.indexOf(".jar!")-4);
                tmp=tmp+"templates";
                cfg.setDirectoryForTemplateLoading(new File(tmp));
            }
            else
            {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            Template temp = cfg.getTemplate("activite.html");

            Map root = new HashMap();
            Document doc = Singleton.instance().getDocument();
            DecimalFormat nf = new DecimalFormat();
            nf.setMaximumFractionDigits(2);
            nf.setMinimumFractionDigits(2);
            SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
            SimpleDateFormat formatShort = new SimpleDateFormat("dd/MM/yyyy");
            root.put("nom", doc.getUtilisateur().getNom() + " " + doc.getUtilisateur().getPrenom());
            root.put("ADELI", doc.getUtilisateur().getAdeli());

            HashMap date = new HashMap();
            date.put("debut", format.format(_debut));
            date.put("fin", format.format(_fin));
            root.put("dates", date);


            Vector<Executant> medecins = new Vector();
            Vector parMedecins = new Vector();
            medecins.add(_data.getUtilisateur());
            if (jcbRemplacants.isSelected()) {
                for (int i = 0; i < _data.getRemplacants().size(); i++) {
                    medecins.add(_data.getRemplacants().get(i));
                }
            }

            for (int i = 0; i < medecins.size(); i++) {
                Executant executant = medecins.get(i);
                int nombre_astreintes = 0;
                int nombre_visites = 0;
                int nombre_creneaux = 0;

                Vector creneaux = new Vector();
                for (int j = 0; j < _data.getCreneaux().size(); j++) {
                    Creneau c = _data.getCreneaux().get(j);
                    Date d = c.getDate();

                    if (d.equals(_debut) || d.equals(_fin) || (d.before(_fin) && d.after(_debut))) {
                        if (c.getExecutant().equals(executant)) {
                            nombre_creneaux++;
                            HashMap creneau = new HashMap();

                            if (c.getAstreinte()) {
                                nombre_astreintes++;
                                creneau.put("astreinte", "Oui");
                            } else {
                                creneau.put("astreinte", "Non");
                            }
                            nombre_visites += c.getVisites().size();

                            creneau.put("date", format.format(c.getDate()));
                            creneau.put("nombre_visites", Integer.toString(c.getVisites().size()));

                            creneaux.add(creneau);
                        }
                    }
                }

                HashMap med = new HashMap();
                med.put("creneaux", creneaux);
                med.put("nombre_creneaux", nombre_creneaux);
                med.put("nombre_visites", nombre_visites);
                med.put("nombre_astreintes", nombre_astreintes);
                med.put("nom", executant.getNom() + ", " + executant.getPrenom());
                parMedecins.add(med);
            }

            root.put("medecins", parMedecins);


            root.put("dateGeneration", formatShort.format(new Date()));

            address = File.createTempFile("activite" + format.format(_debut) + "-" + format.format(_fin), ".tmp");
            address.deleteOnExit();

            File dir = address.getParentFile();

/*            if (jcbDisplayGraphBar.isSelected()) {

                KeypointPNGEncoderAdapter encoder = new KeypointPNGEncoderAdapter();
                encoder.setEncodingAlpha(true);

                jifGraphActivite jif=new jifGraphActivite(_data, _debut, _fin);
                root.put("display_graph_visite_bar", 1);
                FileOutputStream imgwriter2 = new FileOutputStream(dir + "/visitebar.png");
                encoder.encode(jif.getVisiteBarChart(jcbRemplacants.isSelected()).createBufferedImage(640, 480, BufferedImage.BITMASK, null), imgwriter2);
                imgwriter2.close();

                root.put("display_graph_creneau_bar", 1);
                FileOutputStream imgwriter4 = new FileOutputStream(dir + "/creneaubar.png");
                encoder.encode(jif.getVisiteBarChart(jcbRemplacants.isSelected()).createBufferedImage(640, 480, BufferedImage.BITMASK, null), imgwriter4);
                imgwriter4.close();


            } else {*/
                root.put("display_graph_visite_bar", 0);
                root.put("display_graph_creneau_bar", 0);
            /*}

            if (jcbDisplayGraphPie.isSelected()) {

                KeypointPNGEncoderAdapter encoder = new KeypointPNGEncoderAdapter();
                encoder.setEncodingAlpha(true);

                jifGraphActivite jif=new jifGraphActivite(_data, _debut, _fin);

                root.put("display_graph_visite_pie", 1);
                FileOutputStream imgwriter2 = new FileOutputStream(dir + "/visitepie.png");
                encoder.encode(jif.getVisitePieChart(jcbRemplacants.isSelected()).createBufferedImage(640, 480, BufferedImage.BITMASK, null), imgwriter2);
                imgwriter2.close();
                root.put("display_graph_creneau_pie", 1);
                FileOutputStream imgwriter3 = new FileOutputStream(dir + "/creneaupie.png");
                encoder.encode(jif.getCreneauxPieChart(jcbRemplacants.isSelected()).createBufferedImage(640, 480, BufferedImage.BITMASK, null), imgwriter3);
                imgwriter3.close();
            } else {*/
                root.put("display_graph_visite_pie", 0);
                root.put("display_graph_creneau_pie", 0);
            //}

            InputStream imgreader = getClass().getResourceAsStream("/gevi/images/entete.png");
            FileOutputStream imgwriter = new FileOutputStream(dir + "/entete.png");
            byte[] data = new byte[1024];
            int nb = 0;
            while (imgreader.read(data) != -1) {
                imgwriter.write(data);
            }
            imgreader.close();
            imgwriter.close();

            Writer out = new FileWriter(address);
            temp.process(root, out);
            out.flush();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (TemplateException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }

        return address;
    }
}
