/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgNewDocument.java
 *
 * Created on 8 avr. 2009, 15:40:34
 */
package gevi.Views;

import gevi.Model.Depense;
import gevi.Model.Document;
import gevi.Model.Singleton;
import gevi.Model.Utilisateur;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class jdgDepense extends javax.swing.JDialog {

    Document _data;
    Depense _depense = null;

    /** Creates new form jdgNewDocument */
    public jdgDepense(java.awt.Frame parent, boolean modal, Document doc) {
        super(parent, modal);
        initComponents();
        jxdpDate.setDate(new Date());

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }
        _data = doc;

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < _data.getCategories().size(); i++) {
            model.addElement(_data.getCategories().get(i).getNom());
        }
        jcbCategorie.setModel(model);

        jxdpDate.setFormats(new String[]{"EEEEEEEEE dd MMMMMMMMMMM yyyy"});
    }

    public jdgDepense(java.awt.Frame parent, boolean modal, Document doc, Depense dep) {
        super(parent, modal);
        initComponents();
        jxdpDate.setDate(dep.getDate());

        _depense = dep;

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }
        _data = doc;

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < _data.getCategories().size(); i++) {
            model.addElement(_data.getCategories().get(i).getNom());
        }
        jcbCategorie.setModel(model);
        jcbCategorie.setSelectedItem(dep.getCategorie().getNom());

        jcbSource.setSelectedItem(dep.getSource());

        jtfFournisseur.setText(dep.getVendeur());
        jtfObjet.setText(dep.getObjet());
        jftfMontant.setValue(Double.valueOf(dep.getMontant()));

        jxdpDate.setFormats(new String[]{"EEEEEEEEE dd MMMMMMMMMMM yyyy"});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfObjet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jftfMontant = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbCategorie = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jcbSource = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtfFournisseur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dépense");
        setMinimumSize(new java.awt.Dimension(375, 151));

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dépense"));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 1, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Objet :");
        jLabel3.setFocusable(false);
        jPanel3.add(jLabel3);
        jPanel3.add(jtfObjet);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Date :");
        jLabel6.setFocusable(false);
        jPanel3.add(jLabel6);
        jPanel3.add(jxdpDate);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Montant:");
        jLabel7.setFocusable(false);
        jPanel3.add(jLabel7);

        jftfMontant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jftfMontant.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jPanel3.add(jftfMontant);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Catégorie:");
        jLabel8.setFocusable(false);
        jPanel3.add(jLabel8);

        jcbCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jcbCategorie);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Source:");
        jLabel9.setFocusable(false);
        jPanel3.add(jLabel9);

        jcbSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banque", "Espèces" }));
        jPanel3.add(jcbSource);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Fournisseur :");
        jLabel4.setFocusable(false);
        jPanel3.add(jLabel4);
        jPanel3.add(jtfFournisseur);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        if (jtfObjet.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le champ OBJET est vide", "Champ manquant", JOptionPane.ERROR_MESSAGE);
        } else {
            if (jftfMontant.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Le champ MONTANT est vide", "Champ manquant", JOptionPane.ERROR_MESSAGE);
            } else {
                if (jcbCategorie.getSelectedIndex() >= 0) {
                    if (_depense == null) {
                        _depense = new Depense();
                        _data.getDepenses().add(_depense);
                    }
                    _depense.setDate(jxdpDate.getDate());
                    _depense.setCategorie(_data.getCategories().get(jcbCategorie.getSelectedIndex()));
                    _depense.setObjet(jtfObjet.getText());
                    _depense.setVendeur(jtfFournisseur.getText());
                    _depense.setSource((String)jcbSource.getSelectedItem());
                    String tmp=jftfMontant.getText();
                    tmp=tmp.replace(",", ".");
                    tmp=tmp.replace("€", "");
                    _depense.setMontant(Double.parseDouble(tmp));
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Le champ CATEGORIE est vide", "Champ manquant", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_jbtOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtOK;
    private javax.swing.JComboBox jcbCategorie;
    private javax.swing.JComboBox jcbSource;
    private javax.swing.JFormattedTextField jftfMontant;
    private javax.swing.JTextField jtfFournisseur;
    private javax.swing.JTextField jtfObjet;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    // End of variables declaration//GEN-END:variables
}
