/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgRemplacants.java
 *
 * Created on 8 avr. 2009, 13:59:46
 */

package gevi.Views;

import gevi.Model.Creneau;
import gevi.Model.Document;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class jdgRemplacants extends javax.swing.JDialog {

    Document _data;
    /** Creates new form jdgRemplacants */
    public jdgRemplacants(java.awt.Frame parent, boolean modal, Document document) {
        super(parent, modal);
        initComponents();
        _data=document;

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_bleu.png")).getImage());
        mtRemplacants remp=new mtRemplacants(_data.getRemplacants());
        jxtRemplaçants.setModel(remp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtAjouter = new javax.swing.JButton();
        jbtSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtRemplaçants = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remplaçants"));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 390));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 1, 1));

        jbtAjouter.setText("Ajouter Remplaçant");
        jbtAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAjouterActionPerformed(evt);
            }
        });
        jPanel4.add(jbtAjouter);

        jbtSupprimer.setText("Supprimer remplaçant");
        jbtSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSupprimerActionPerformed(evt);
            }
        });
        jPanel4.add(jbtSupprimer);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jxtRemplaçants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jxtRemplaçants.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(jxtRemplaçants);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAjouterActionPerformed
        jdgRemplacant remp=new jdgRemplacant(MainWindow.getMainWindow(), true,_data.getRemplacants());
        remp.setVisible(true);
        jxtRemplaçants.repaint();
}//GEN-LAST:event_jbtAjouterActionPerformed

    private void jbtSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSupprimerActionPerformed
        int nb=jxtRemplaçants.getSelectedRow();

        if (nb>=0)
        {
            boolean isUsed=false;
            for (int i=0; i<_data.getCreneaux().size(); i++)
            {
                Creneau cren=(Creneau) _data.getCreneaux().get(i);
                if (cren.getExecutant()==_data.getRemplacants().get(nb))
                {
                    isUsed=true;
                }
            }
            if (!isUsed)
            {
                _data.getRemplacants().remove(nb);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ce médecin possède un créneau, il ne peut donc pas être supprimé.");
            }
            jxtRemplaçants.repaint();
        }
    }//GEN-LAST:event_jbtSupprimerActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAjouter;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtSupprimer;
    private org.jdesktop.swingx.JXTable jxtRemplaçants;
    // End of variables declaration//GEN-END:variables

}
