/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgSaisie.java
 *
 * Created on 7 avr. 2009, 18:11:54
 */

package gevi.Views;
import java.awt.Graphics;
import gevi.Model.Creneau;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Visite;
import java.awt.BorderLayout;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author root
 */
public class jdgSaisieRapide extends javax.swing.JDialog {

    Creneau _data;
    
    /** Creates new form jdgSaisie */
    public jdgSaisieRapide(java.awt.Frame parent, boolean modal,Creneau creneau) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        this.setTitle("Saisie rapide de visites");
        _data=creneau;
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_rouge.png")).getImage());
        
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtVisites = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jbtAddVisite = new javax.swing.JButton();
        jbtDelVisite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Versement");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jxtVisites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jxtVisites);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtAddVisite.setText("Ajouter une visite");
        jbtAddVisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddVisiteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAddVisite);

        jbtDelVisite.setText("Supprimer une visite");
        jbtDelVisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDelVisiteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtDelVisite);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jbtDelVisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelVisiteActionPerformed
        _data.getVisites().remove(jxtVisites.getSelectedRow());
        repaint();
    }//GEN-LAST:event_jbtDelVisiteActionPerformed

    private void jbtAddVisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddVisiteActionPerformed
        _data.getVisites().add(new Visite());
        repaint();
    }//GEN-LAST:event_jbtAddVisiteActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAddVisite;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtDelVisite;
    private javax.swing.JButton jbtOK;
    private org.jdesktop.swingx.JXTable jxtVisites;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        mtSaisieRapideVisites mta=new mtSaisieRapideVisites(_data);
        jxtVisites.setModel(mta);
        jxtVisites.setDefaultRenderer(String.class, mta);
        jxtVisites.setDefaultRenderer(Double.class, mta);
        jxtVisites.setDefaultRenderer(Integer.class, mta);
        jxtVisites.setDefaultRenderer(Boolean.class, mta);
        jxtVisites.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

}
