/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgSelectionCreneau.java
 *
 * Created on 9 avr. 2009, 13:34:15
 */
package gevi.Views;

import gevi.Model.Creneau;
import gevi.Model.Document;
import gevi.Model.Versement;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author root
 */
public class jdgSelectionVersements extends javax.swing.JDialog {

    Document _data;
    boolean _rapport = false;
    Vector _versements=new Vector();

    /** Creates new form jdgSelectionCreneau */
    /*    public jdgSelectionVersements(java.awt.Frame parent, boolean modal, Document data, Date debut, Date fin, int index,int rapport) {
    super(parent, modal);
    initComponents();

    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    GraphicsDevice gs = ge.getDefaultScreenDevice();
    DisplayMode dmode = gs.getDisplayMode();

    if (dmode != null) {
    int screenWidth = dmode.getWidth();
    int screenHeight = dmode.getHeight();
    this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
    }

    _data = data;

    this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_rouge.png")).getImage());

    //String[] liste=new String[_data.getCreneaux().size()];
    DefaultListModel model = new DefaultListModel();
    for (int i = 0; i < _data.getCreneaux().size(); i++) {
    Creneau cren = (Creneau) _data.getCreneaux().get(i);
    //liste[i]=cren.getName();
    model.addElement(cren.getName());
    }
    jlsCreneaux.setModel(model);
    }*/
    public jdgSelectionVersements(java.awt.Frame parent, boolean modal, Document data, Date debut, Date fin, int index, boolean rapport) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_violet.png")).getImage());
        _data = data;
        _rapport = rapport;

        //String[] liste=new String[_data.getCreneaux().size()];
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < _data.getVersements().size(); i++) {
            Versement vers = _data.getVersements().get(i);
            Date date = vers.getDate();
            if (date.before(fin) && date.after(debut)) {
                if ((index == 0)||(index==1)) {
                    _versements.add(vers);
                    model.addElement(vers.getName());
                } else {
                    if (vers.getExecutant().equals(_data.getRemplacants().get(index - 2))) {
                        _versements.add(vers);
                        model.addElement(vers.getName());
                    }
                }
            }            
        }
        jlsVersements.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsVersements = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(378, 367));
        setResizable(false);

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selection des versements"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        jlsVersements.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlsVersements);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        int[] indices = jlsVersements.getSelectedIndices();
        for (int i = 0; i < indices.length; i++) {
            Versement vers = (Versement) _versements.get(indices[i]);
            if (!_rapport) {
                MainWindow.getMainWindow().displayWindow(MainWindow.CST_VERSEMENT, vers);
            } else {
                MainWindow.getMainWindow().displayWindow(MainWindow.CST_RAPPORT_VERSEMENT, vers);
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtOK;
    private javax.swing.JList jlsVersements;
    // End of variables declaration//GEN-END:variables
}
