/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgTransfert.java
 *
 * Created on 28 juin 2009, 13:59:27
 */
package gevi.Views;

import gevi.Model.Document;
import gevi.Model.Operation;
import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author root.106572700130
 */
public class jdgTransfert extends javax.swing.JDialog {

    Document _document;

    /** Creates new form jdgTransfert */
    public jdgTransfert(java.awt.Frame parent, boolean modal, Document doc) {
        super(parent, modal);
        initComponents();

        this.setPreferredSize(new Dimension(315,114));

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_rose.png")).getImage());

        _document = doc;
        jxdpDate.setDate(new Date());
        jftMontant.setValue(new Double(0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbtAnnuler = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jrbtoCash = new javax.swing.JRadioButton();
        jrbFromCash = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();
        jftMontant = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(315, 114));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(315, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(315, 33));

        jbtAnnuler.setText("Annuler");
        jbtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAnnuler);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setMinimumSize(new java.awt.Dimension(315, 85));
        jPanel2.setPreferredSize(new java.awt.Dimension(315, 85));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 1, 1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Type de transfert"));
        jPanel3.setPreferredSize(new java.awt.Dimension(158, 85));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        buttonGroup1.add(jrbtoCash);
        jrbtoCash.setText("Banque -> Caisse");
        jPanel3.add(jrbtoCash);

        buttonGroup1.add(jrbFromCash);
        jrbFromCash.setSelected(true);
        jrbFromCash.setText("Caisse -> Banque");
        jPanel3.add(jrbFromCash);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfert"));
        jPanel4.setPreferredSize(new java.awt.Dimension(157, 85));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jxdpDate.setPreferredSize(new java.awt.Dimension(315, 114));
        jPanel4.add(jxdpDate);

        jftMontant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel4.add(jftMontant);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtAnnulerActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        Double val=Double.parseDouble(jftMontant.getText().replace("€", "").replace(",","."));
        if (val <= 0.0) {
            JOptionPane.showMessageDialog(this, "Le montant est vide.", "Pas de somme entrée", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Operation op = new Operation(jxdpDate.getDate(), val);

            if (jrbFromCash.isSelected()) {
                _document.getBanque().getOperationsFromCash().add(op);
            } else {
                _document.getBanque().getOperationsToCash().add(op);
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtAnnuler;
    private javax.swing.JButton jbtOK;
    private javax.swing.JFormattedTextField jftMontant;
    private javax.swing.JRadioButton jrbFromCash;
    private javax.swing.JRadioButton jrbtoCash;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    // End of variables declaration//GEN-END:variables
}
