/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCreneau.java
 *
 * Created on 9 avr. 2009, 15:02:03
 */
package gevi.Views;

import gevi.Model.Categorie;
import gevi.Model.Creneau;
import gevi.Model.Depense;
import gevi.Model.Visite;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Singleton;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author root
 */
public class jifFrais extends javax.swing.JInternalFrame {

    Document _data;
    Vector<Depense> _frais;
    Date _debut;
    Date _fin;

    /** Creates new form jifCreneau */
    public jifFrais(Document data, Date debut, Date fin) {
        initComponents();
        _data = data;
        SimpleDateFormat f = new SimpleDateFormat("EEEEEEEEE dd MMMMMMMMMMM yyyy");
        this.setTitle("Liste des dépenses du " + f.format(debut) + " au " + f.format(fin));

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        int selectedCat[] = new int[data.getCategories().size()];
        DefaultListModel model = new DefaultListModel();
        for (int cpt = 0; cpt < data.getCategories().size(); cpt++) {
            model.addElement(data.getCategories().get(cpt).getNom());
            selectedCat[cpt] = cpt;
        }
        jlsCategories.setModel(model);

        _debut = debut;
        _fin = fin;

        _frais = new Vector();
        mtFrais tableModel = new mtFrais(_frais);
        jxtDepenses.setModel(tableModel);
        jxtDepenses.setDefaultRenderer(String.class, tableModel);
        jxtDepenses.setDefaultRenderer(Double.class, tableModel);
        jxtDepenses.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        refreshFrais();

        jlsCategories.setSelectedIndices(selectedCat);

        pack();
    }

    private void refreshFrais() {
        _frais.clear();

        Vector<Categorie> categories = Singleton.instance().getDocument().getCategories();
        Vector<Depense> depenses = Singleton.instance().getDocument().getDepenses();
        Object selectedCategories[] = (Object[]) jlsCategories.getSelectedValues();
        for (int i = 0; i < depenses.size(); i++) {
            Depense d = depenses.get(i);
            Date da = d.getDate();
            if ((da.before(_fin) && da.after(_debut)) || (da.equals(_fin)) || (da.equals(_debut))) {

                String categorie = d.getCategorie().getNom();
                boolean selectionne = false;
                for (int cpt = 0; cpt < selectedCategories.length; cpt++) {
                    if (((String) selectedCategories[cpt]).equals(categorie)) {
                        selectionne = true;
                        break;
                    }
                }
                if (selectionne) {
                    _frais.add(d);
                }
            }
        }
        mtFrais tableModel = new mtFrais(_frais);
        jxtDepenses.setModel(tableModel);
        jxtDepenses.setDefaultRenderer(String.class, tableModel);
        jxtDepenses.setDefaultRenderer(Double.class, tableModel);
        jxtDepenses.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsCategories = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxtDepenses = new org.jdesktop.swingx.JXTable();
        jPanel6 = new javax.swing.JPanel();
        jbtEditer = new javax.swing.JButton();
        jbtSupprimer = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_violet.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catégories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jlsCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlsCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlsCategories);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jxtDepenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jxtDepenses);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jbtEditer.setText("Editer");
        jbtEditer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditerActionPerformed(evt);
            }
        });
        jPanel6.add(jbtEditer);

        jbtSupprimer.setText("Supprimer");
        jbtSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSupprimerActionPerformed(evt);
            }
        });
        jPanel6.add(jbtSupprimer);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        MainWindow.getMainWindow().closeWindow(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed

    private void jlsCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlsCategoriesValueChanged
        refreshFrais();
}//GEN-LAST:event_jlsCategoriesValueChanged

    private void jbtEditerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditerActionPerformed

        if (jxtDepenses.getSelectedRow() >= 0) {
            Depense d = _frais.get(jxtDepenses.getSelectedRow());
            jdgDepense jdg = new jdgDepense(MainWindow.getMainWindow(), true, _data, d);
            jdg.setVisible(true);
        }
        refreshFrais();
}//GEN-LAST:event_jbtEditerActionPerformed

    private void jbtSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSupprimerActionPerformed
        Depense d = _frais.get(jxtDepenses.getSelectedRow());
        _data.getDepenses().remove(d);
        refreshFrais();
}//GEN-LAST:event_jbtSupprimerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtEditer;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtSupprimer;
    private javax.swing.JList jlsCategories;
    private org.jdesktop.swingx.JXTable jxtDepenses;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);
        refreshFrais();
    }
}
