/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifCreneau.java
 *
 * Created on 9 avr. 2009, 15:02:03
 */
package gevi.Views;

import gevi.Model.Creneau;
import gevi.Model.Document;
import gevi.Model.Executant;
import gevi.Model.Singleton;
import gevi.Model.Versement;
import gevi.Model.Visite;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class jifVersement extends javax.swing.JInternalFrame {

    Document _document;
    Executant _executant;
    Vector<Object> _operations;
    Vector<Boolean> _reverser;
    double _total = 0;
    double _versement = 0;
    Date _date = new Date();
    Versement _data;

    /** Creates new form jifCreneau */
    public jifVersement(Document d, Versement data) {
        initComponents();
        _data = data;
        this.setTitle(data.getName());

        try {
            this.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        jxdpDate.setFormats(new String[]{"EEEEEEEEE dd MMMMMMMMMMM yyyy"});
        jxdpDate.setDate(_data.getDate());

        jtfDivers.setText(_data.getDivers());
        jtfMedecin.setText(_data.getExecutant().getNom() + ", " + _data.getExecutant().getPrenom());

        _operations = new Vector();
        _reverser = new Vector();
        _document=d;

        int id = _data.getId();
        for (int i = 0; i < _document.getCreneaux().size(); i++) {
            Creneau c = _document.getCreneaux().get(i);
            if (c.getVersementId() == id) {
                _operations.add(c);
                _reverser.add(Boolean.TRUE);
            }

            for (int j = 0; j < c.getVisites().size(); j++) {
                if (c.getVisites().get(j).getVersementId() == id) {
                    _operations.add(c.getVisites().get(j));
                    _reverser.add(Boolean.TRUE);
                }
            }
        }

        mtOperationSelect model = new mtOperationSelect(_operations, _reverser);
        jxtOperations.setModel(model);
        jxtOperations.setDefaultRenderer(String.class, model);
        jxtOperations.setDefaultRenderer(Double.class, model);
        jxtOperations.setDefaultRenderer(Integer.class, model);

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtOperations = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jftfSomme = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftfVersement = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfMedecin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jxdpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jtfDivers = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gevi/images/sos_violet.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opérations"));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 230));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout(2, 2));

        jxtOperations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jxtOperations.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jxtOperations.setAutoscrolls(false);
        jxtOperations.setCellSelectionEnabled(false);
        jxtOperations.setEditable(false);
        jxtOperations.setSortable(false);
        jScrollPane1.setViewportView(jxtOperations);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Montant des visites :");
        jPanel2.add(jLabel3);

        jftfSomme.setEditable(false);
        jPanel2.add(jftfSomme);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Montant du versement :");
        jPanel2.add(jLabel4);

        jftfVersement.setEditable(false);
        jPanel2.add(jftfVersement);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 1, 1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Médecin :");
        jPanel4.add(jLabel5);

        jtfMedecin.setEditable(false);
        jPanel4.add(jtfMedecin);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Date:");
        jPanel4.add(jLabel1);

        jxdpDate.setEditable(false);
        jPanel4.add(jxdpDate);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Divers :");
        jPanel4.add(jLabel2);
        jPanel4.add(jtfDivers);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(jLabel6);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        MainWindow.getMainWindow().closeWindow(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        MainWindow.getMainWindow().closeWindow(this);
        this.setVisible(false);
}//GEN-LAST:event_jbtOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtOK;
    private javax.swing.JFormattedTextField jftfSomme;
    private javax.swing.JFormattedTextField jftfVersement;
    private javax.swing.JTextField jtfDivers;
    private javax.swing.JTextField jtfMedecin;
    private org.jdesktop.swingx.JXDatePicker jxdpDate;
    private org.jdesktop.swingx.JXTable jxtOperations;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        super.paint(g);

        _total = 0;
        _versement = 0;
        for (int i = 0; i < _reverser.size(); i++) {
            if (_reverser.get(i).equals(Boolean.TRUE)) {
                Object obj = _operations.get(i);
                if (obj instanceof Creneau) {
                    Creneau c = (Creneau) obj;
                    if (c.getAstreinte() && c.getAstreintePayee()) {
                        _versement = _versement + _document.getParametres().getTarifAstreinte();
                        _total = _total + _document.getParametres().getTarifAstreinte();
                    }
                }

                if (obj instanceof Visite) {
                    Visite v = (Visite) obj;
                    if (v.getPaye() && (v.getVersementId() < 0)) {
                        _versement = _versement + (1 - _document.getParametres().getPrelevement()) * v.getTotal();
                        _total = _total + v.getTotal();
                    }
                }
            }
        }

        jftfSomme.setValue(_total);
        jftfVersement.setValue(_versement);
    }
}
